artifact_uri: file:C:/Users/anash/Downloads/qualityagent_phase2/runs/mlflow/388703001279444204/4cda0ba561fe4152a11bff9381c39bd3/artifacts
end_time: 1781020247957
entry_point_name: ''
experiment_id: '388703001279444204'
lifecycle_stage: active
run_id: 4cda0ba561fe4152a11bff9381c39bd3
run_name: run_v1
source_name: ''
source_type: 4
source_version: ''
start_time: 1781007661005
status: 3
tags: []
user_id: anash
